### ISSUE TITLE
User and Password missing

### ISSUE THREAD

**Issue by henkkl** [apazga/smappee-domoticz-bash#2]
Hi apazga,
Great script! and it's working fine after I made some changes :-)
What's missing in the script are the user and password for domoticz
So I've made two string variables: USER and PASS
Then the code to send it to Domoticz will be:
curl -u $USER:$PASS "${DOMOTICZ_URL}/json.htm?type=command&param=udevice&idx=${DOMOTICZ_VOLTS_IDX}&nvalue=0&svalue=${VOLTS}"

And off course also for the other curl statements. 
With kind regards
Henkkl

**Comment by apazga** [comment]
Hi!

I don't use user/password for this script. I'm using Domoticz setting to include a list of IPs that doesn't need authentication.

But I'll include them in the next release! 👍

**Comment by apazga** [comment]
**Updated**:  New develop branch version include authentication ;)
I will be testing it a few days and if everything is OK, I'll merge the code to the master branch ;).

**Comment by henkkl** [comment]
Thnx abel,
Keep up the good work. :-)
Kind Regards,
Henk Kleinee

Op 4 apr. 2017 22:44 schreef "Abel Paz" <notifications@github.com>:
